### ISSUE TITLE
Cannot execute the code on mobile

### ISSUE THREAD

**Issue by mycodingstudio** [axiftaj/WhatsApp-UI-Design-Flutter#1]
Hi Author, 
any idea why my ide output these error when running your code?
<img width="1337" alt="Screen Shot 2022-03-25 at 9 02 24 AM" src="https://user-images.githubusercontent.com/86642688/160034791-f2a7d11f-d75e-488a-b4af-1ae7f05e7da4.png">

**Comment by axiftaj** [comment]
Hello, 

Thank you for your feedback. This error is because some of the file for android didn't get uploaded when i pushed the code to github. Sorry for inconvenience. I had just fixed the issue and update the code. You can clone it again. 

Thank you

**Comment by axiftaj** [comment]
Hello,

This has been fixed, while pushing code to github some of the android files
got missing. I added it and pushed code to github.

Thank you for positive feedback

Best regards
